//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 03:29:52 PM MSK 
//


package com.skat.smev.fns.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.skat.smev.fns.domain.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="СведЮЛ">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="НаимОрг" use="required" type="{urn://x-artefacts-fns-inn/commons/4.0.0}string-1000" />
 *                 &lt;attribute name="ИННЮЛ" use="required" type="{urn://x-artefacts-fns-inn/commons/4.0.0}ИННЮЛТип" />
 *                 &lt;attribute name="ОГРН" use="required" type="{urn://x-artefacts-fns-inn/commons/4.0.0}ОГРН" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="СведФЛ" type="{urn://x-artefacts-fns-inn/commons/4.0.0}СведФЛТип"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ИдЗапрос" use="required" type="{urn://x-artefacts-fns-inn/commons/4.0.0}ИдЗапросТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "\u0441\u0432\u0435\u0434\u042e\u041b",
    "\u0441\u0432\u0435\u0434\u0424\u041b"
})
@XmlRootElement(name = "FNSINNSingularRequest", namespace = "urn://x-artefacts-fns-inn-singular/root/270-18/4.0.1")
public class FNSINNSingularRequest {

    @XmlElement(name = "\u0421\u0432\u0435\u0434\u042e\u041b", namespace = "urn://x-artefacts-fns-inn-singular/root/270-18/4.0.1", required = true)
    protected FNSINNSingularRequest.СведЮЛ сведЮЛ;
    @XmlElement(name = "\u0421\u0432\u0435\u0434\u0424\u041b", namespace = "urn://x-artefacts-fns-inn-singular/root/270-18/4.0.1", required = true)
    protected СведФЛТип сведФЛ;
    @XmlAttribute(name = "\u0418\u0434\u0417\u0430\u043f\u0440\u043e\u0441", required = true)
    protected String идЗапрос;

    /**
     * Gets the value of the сведЮЛ property.
     * 
     * @return
     *     possible object is
     *     {@link FNSINNSingularRequest.СведЮЛ }
     *     
     */
    public FNSINNSingularRequest.СведЮЛ getСведЮЛ() {
        return сведЮЛ;
    }

    /**
     * Sets the value of the сведЮЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link FNSINNSingularRequest.СведЮЛ }
     *     
     */
    public void setСведЮЛ(FNSINNSingularRequest.СведЮЛ value) {
        this.сведЮЛ = value;
    }

    /**
     * Gets the value of the сведФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link СведФЛТип }
     *     
     */
    public СведФЛТип getСведФЛ() {
        return сведФЛ;
    }

    /**
     * Sets the value of the сведФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link СведФЛТип }
     *     
     */
    public void setСведФЛ(СведФЛТип value) {
        this.сведФЛ = value;
    }

    /**
     * Gets the value of the идЗапрос property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдЗапрос() {
        return идЗапрос;
    }

    /**
     * Sets the value of the идЗапрос property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдЗапрос(String value) {
        this.идЗапрос = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="НаимОрг" use="required" type="{urn://x-artefacts-fns-inn/commons/4.0.0}string-1000" />
     *       &lt;attribute name="ИННЮЛ" use="required" type="{urn://x-artefacts-fns-inn/commons/4.0.0}ИННЮЛТип" />
     *       &lt;attribute name="ОГРН" use="required" type="{urn://x-artefacts-fns-inn/commons/4.0.0}ОГРН" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class СведЮЛ {

        @XmlAttribute(name = "\u041d\u0430\u0438\u043c\u041e\u0440\u0433", required = true)
        protected String наимОрг;
        @XmlAttribute(name = "\u0418\u041d\u041d\u042e\u041b", required = true)
        protected String иннюл;
        @XmlAttribute(name = "\u041e\u0413\u0420\u041d", required = true)
        protected String огрн;

        /**
         * Gets the value of the наимОрг property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНаимОрг() {
            return наимОрг;
        }

        /**
         * Sets the value of the наимОрг property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНаимОрг(String value) {
            this.наимОрг = value;
        }

        /**
         * Gets the value of the иннюл property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getИННЮЛ() {
            return иннюл;
        }

        /**
         * Sets the value of the иннюл property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setИННЮЛ(String value) {
            this.иннюл = value;
        }

        /**
         * Gets the value of the огрн property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getОГРН() {
            return огрн;
        }

        /**
         * Sets the value of the огрн property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setОГРН(String value) {
            this.огрн = value;
        }

    }

}
