//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 03:29:52 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://x-artefacts-smev-gov-ru/supplementary/commons/1.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.skat.smev.fns.domain;
