//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 03:29:52 PM MSK 
//


package com.skat.smev.fns.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PhysicalPersonDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalPersonDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PhysicalPersonName" type="{urn://x-artefacts-fns-inn/commons/4.0.0}PhysicalPersonNameType"/>
 *         &lt;element name="IdentityDocument" type="{urn://x-artefacts-fns-inn/commons/4.0.0}IdentityDocumentType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BirthDate" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="BirthPlace" type="{urn://x-artefacts-fns-inn/commons/4.0.0}string-255" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalPersonDataType", namespace = "urn://x-artefacts-fns-inn/commons/4.0.0", propOrder = {
    "physicalPersonName",
    "identityDocument"
})
public class PhysicalPersonDataType {

    @XmlElement(name = "PhysicalPersonName", required = true)
    protected PhysicalPersonNameType physicalPersonName;
    @XmlElement(name = "IdentityDocument", required = true)
    protected IdentityDocumentType identityDocument;
    @XmlAttribute(name = "BirthDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlAttribute(name = "BirthPlace")
    protected String birthPlace;

    /**
     * Gets the value of the physicalPersonName property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalPersonNameType }
     *     
     */
    public PhysicalPersonNameType getPhysicalPersonName() {
        return physicalPersonName;
    }

    /**
     * Sets the value of the physicalPersonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalPersonNameType }
     *     
     */
    public void setPhysicalPersonName(PhysicalPersonNameType value) {
        this.physicalPersonName = value;
    }

    /**
     * Gets the value of the identityDocument property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityDocumentType }
     *     
     */
    public IdentityDocumentType getIdentityDocument() {
        return identityDocument;
    }

    /**
     * Sets the value of the identityDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityDocumentType }
     *     
     */
    public void setIdentityDocument(IdentityDocumentType value) {
        this.identityDocument = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthPlace(String value) {
        this.birthPlace = value;
    }

}
