//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.12 at 03:29:52 PM MSK 
//


package com.skat.smev.fns.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Сведения о физическом лице
 * 
 * <p>Java class for СведФЛТип complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="СведФЛТип">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ФИО" type="{urn://x-artefacts-fns-inn/commons/4.0.0}ФИОТип"/>
 *         &lt;element name="УдЛичнФЛ" type="{urn://x-artefacts-fns-inn/commons/4.0.0}УдЛичнФЛТип"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ДатаРожд" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="МестоРожд" type="{urn://x-artefacts-fns-inn/commons/4.0.0}string-255" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u0421\u0432\u0435\u0434\u0424\u041b\u0422\u0438\u043f", namespace = "urn://x-artefacts-fns-inn/commons/4.0.0", propOrder = {
    "\u0444\u0438\u043e",
    "\u0443\u0434\u041b\u0438\u0447\u043d\u0424\u041b"
})
//СведФЛТип
public class СведФЛТип {

    @XmlElement(name = "\u0424\u0418\u041e", required = true)
    protected ФИОТип фио;
    @XmlElement(name = "\u0423\u0434\u041b\u0438\u0447\u043d\u0424\u041b", required = true)
    protected УдЛичнФЛТип удЛичнФЛ;
    @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0420\u043e\u0436\u0434", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar датаРожд;
    @XmlAttribute(name = "\u041c\u0435\u0441\u0442\u043e\u0420\u043e\u0436\u0434")
    protected String местоРожд;

    /**
     * Gets the value of the фио property.
     * 
     * @return
     *     possible object is
     *     {@link ФИОТип }
     *     
     */
    public ФИОТип getФИО() {
        return фио;
    }

    /**
     * Sets the value of the фио property.
     * 
     * @param value
     *     allowed object is
     *     {@link ФИОТип }
     *     
     */
    public void setФИО(ФИОТип value) {
        this.фио = value;
    }

    /**
     * Gets the value of the удЛичнФЛ property.
     * 
     * @return
     *     possible object is
     *     {@link УдЛичнФЛТип }
     *     
     */
    public УдЛичнФЛТип getУдЛичнФЛ() {
        return удЛичнФЛ;
    }

    /**
     * Sets the value of the удЛичнФЛ property.
     * 
     * @param value
     *     allowed object is
     *     {@link УдЛичнФЛТип }
     *     
     */
    public void setУдЛичнФЛ(УдЛичнФЛТип value) {
        this.удЛичнФЛ = value;
    }

    /**
     * Gets the value of the датаРожд property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getДатаРожд() {
        return датаРожд;
    }

    /**
     * Sets the value of the датаРожд property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setДатаРожд(XMLGregorianCalendar value) {
        this.датаРожд = value;
    }

    /**
     * Gets the value of the местоРожд property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getМестоРожд() {
        return местоРожд;
    }

    /**
     * Sets the value of the местоРожд property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setМестоРожд(String value) {
        this.местоРожд = value;
    }

}
